/* CHALLENGE
Given a two strings, write an algorithm to check if they are anagrams
of each other. Return true if the pass the test and false if they
don't. E.g
    isAnagram('silent', 'listen') // should return true
*/

//parameters:
//return:
//examples:
//pseudocode:

function isAnagram(stringA, stringB) {

  const sanitizeString = function (str) {
      return str.toLowerCase().replace(/[^a-z\d]/g, '').split('').sort().join('');
  }

  return sanitizeString(stringA) == sanitizeString(stringB)

}

module.exports = isAnagram